version: "3.8"
services:
  server:
    environment:
      - SAVE_FILE
      - FACTORIO_PORT
      - RCON_PORT
      - RCON_PASSWORD
    build:
      context: .
      dockerfile: ./factorio.dockerfile
      args:
        # These args are populated from .env
        UBUNTU_VERSION: "${UBUNTU_VERSION}"
        FACTORIO_VERSION: "${FACTORIO_VERSION}"
        FACTORIO_ROOT: "${FACTORIO_ROOT}"
    stop_signal: SIGTERM
    ports:
      - "${FACTORIO_PORT}:${FACTORIO_PORT}/udp" # server
      - "${RCON_PORT}:${RCON_PORT}/tcp" # rcon
    volumes:
      - ./saves:${FACTORIO_ROOT}/saves
      - ./mods:/${FACTORIO_ROOT}/mods
    stop_grace_period: 10s # Allow time for server to save
